services:
  db:
    image: postgres:14
    container_name: word_guess_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: word_guess_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: word_guess_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@db/word_guess_dev
      SECRET_KEY_BASE: QQPvnMmYvRPdGY5yqJs24UpLBDNvT22kzC4wladlybcFT38KfkJK2QQ+nLLgRbK/
      PHX_HOST: localhost
      MIX_ENV: dev
    ports:
      - "4000:4000"
    command: sh -c "mix deps.get && mix ecto.create && mix ecto.migrate && mix phx.server"

volumes:
  postgres_data: